# Generated by Django 3.2.9 on 2021-11-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('desc', models.TextField()),
                ('nb_of_players', models.IntegerField()),
                ('team_size', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('LO', 'Easy'), ('MD', 'Intermediate'), ('HI', 'Hard')], default='LO', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('desc', models.TextField()),
                ('nb_of_players', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('challenges', models.ManyToManyField(to='dare_app.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(editable=False, upload_to='TO_BE_DEFINED')),
                ('validations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partyAdmin', to=settings.AUTH_USER_MODEL)),
                ('challenge_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dare_app.challengecollection')),
                ('players', models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='equipments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dare_app.equipment'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='proof_of_success',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dare_app.proofofsuccess'),
        ),
    ]
